version: '3.9'

services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - SECRET=secret
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=avitoshop
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 5